### PR TITLE
with_exception is Python 3.x only

### PR DESCRIPTION
**Pull request by andybak**
This seemed the simplest way to handle 2.x although it could be improved if by using the traceback module.

### CODE REVIEW

**Comment by SeanHayes** [comment]
Needs CI fixes.

Would the `six` library's `raise_from` or `reraise` be appropriate here?

**Comment by andybak** [comment]
From a brief glance it looks like #10 solves this in the way you suggest. But it depends on #8 being accepted. I'll close this PR and wait for those two to arrive.

**Comment by andybak** [comment]
I'm a bit stuck with this now. #10 is a better fix than mine but it's stuck on #8 and I don't know enough to help with getting that merged. If I improve this to use six. raise_from or reraise is it likely to get accepted until #10 is ready?

**Comment by SeanHayes** [comment]
#8 has been merged, let's see if #10 gets rebased and resubmitted soon.

**Comment by SeanHayes** [comment]
#10 got merged.

**Pull request closed without merging**
